# Generated by Django 3.0.8 on 2020-08-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.BooleanField(default=True),
        ),
    ]
