# Generated by Django 3.0.8 on 2020-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_auto_20200803_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdesc',
            name='room_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomdesc',
            name='room_image',
            field=models.ImageField(default='SOME STRING', upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='roomdesc',
            name='room_price',
            field=models.IntegerField(default=0),
        ),
    ]
