# Generated by Django 3.0.8 on 2020-08-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookroom', '0002_auto_20200803_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
